#  飞书  # 不要随意修改example中配置的顺序和空格，否则docker的sed脚本会执行出错
APP_ID: cli_a49d71ba84be500e
APP_SECRET: kMH1BBqFuKQUukhmXvLalhfx7y7McBBD
APP_ENCRYPT_KEY: pX7clWNDDJbRQusBpr0Uehq6nbqTR0Fm
APP_VERIFICATION_TOKEN: ev9XhMeIjFh1hOyFE0POugMDSGgxhPxP
# 请确保和飞书应用管理平台中的设置一致
BOT_NAME: ChatGPT
# openAI key 支持负载均衡 可以填写多个key 用逗号分隔
OPENAI_KEY: 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,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,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,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,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,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
# 服务器配置
HTTP_PORT: 9000
HTTPS_PORT: 9001
USE_HTTPS: false
CERT_FILE: cert.pem
KEY_FILE: key.pem
# openai 地址, 一般不需要修改, 除非你有自己的反向代理
API_URL: https://api.openai.com
# 代理设置, 例如 "http://127.0.0.1:7890", ""代表不使用代理
HTTP_PROXY: ""
